/*these are global variable to need to use within screens */
global.id_ls = -1;
global.content_ls = "";
global.lat_ls = -1;
global.lng_ls = -1;
global.user_id_ls = -1;
global.courier_id_ls = -1;
global.apptoken = "";
global.status = -1;
global.role = -1;
global.ls_length = -1;
global.ls_index = -1;
global.reachEnd = 0;
global.display  = 0;
global.username = "";
global.phoneNum = "Please enter phone number";
global.locFrom  = -1;
global.locTo    = -1;
global.time     = -1;
